backend:
  name: git-gateway
  branch: source

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: news
    label: News
    folder: content/news
    fields:
      - name: nocard
        label: Keine Hintergrundkarte
        widget: Boolean
        default: false
      - name: title
        label: Titel
        widget: string
      - name: date
        label: Datum
        widget: datetime
